version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: focus-mysql
    restart: always
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: focus_db
      MYSQL_ROOT_PASSWORD: focus
      MYSQL_USER: focus
      MYSQL_PASSWORD: focus
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - focus-network

networks:
  focus-network:
    driver: bridge
