version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: focus-mysql
    restart: always
    ports:
      - 13307:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: focus_db
      MYSQL_ROOT_PASSWORD: focus
      MYSQL_USER: focus
      MYSQL_PASSWORD: focus
    command: --default-time-zone='+09:00'
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - focus-network

volumes:
  mysql-data:

networks:
  focus-network:
    driver: bridge
