version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - focus-network

  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: focus-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - focus-network

volumes:
  mysql-data:

networks:
  focus-network:
    driver: bridge
