# docker-compose-dev.yml
version: '3.8'

services:
  app-blue:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app-blue
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    networks:
      - focus-network

  app-green:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app-green
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    networks:
      - focus-network

  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    container_name: focus-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      - --default-time-zone=+09:00
      - -bind-address=0.0.0.0
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - focus-network

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: focus-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - focus-network

volumes:
  mysql-data:
  redis-data:

networks:
  focus-network:
    driver: bridge
