version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - focus-network

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: focus-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - focus-network

volumes:
  redis-data:

networks:
  focus-network:
    driver: bridge
