# docker-compose.yml (prod)
version: '3.8'

services:
  app-blue:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app-blue
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
    networks:
      - focus-network

  app-green:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: focus-to-levelup-app-green
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
    networks:
      - focus-network

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: focus-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - focus-network

volumes:
  redis-data:

networks:
  focus-network:
    driver: bridge
