# application-dev.yml (개발 서버용 - Docker Compose MySQL)
spring:
  datasource-data:
    jdbc-url: jdbc:mysql://mysql:3306/focus_db?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-meta:
    jdbc-url: jdbc:mysql://mysql:3306/focus_meta_db?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_META_USERNAME}
    password: ${DB_META_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
      initialize-schema: always

  sql:
    init:
      mode: always
      data-locations: ${MASTER_DATA_PATH}
      encoding: UTF-8
      continue-on-error: false

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN
