# application-dev.yml (개발 서버용 - ECS/Docker Compose)
spring:
  datasource-data:
    jdbc-url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:focus_db}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-meta:
    jdbc-url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_META_NAME:focus_meta_db}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_META_USERNAME}
    password: ${DB_META_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
      initialize-schema: always

  sql:
    init:
      mode: always
      data-locations: ${MASTER_DATA_PATH}
      encoding: UTF-8
      continue-on-error: false

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN
