# application-dev.yml (개발 서버용 - Docker Compose MySQL)
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/focus_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
