# application-prod.yml (프로덕션용 - AWS RDS)
spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  datasource-data:
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource-meta:
    jdbc-url: ${DB_META_URL}
    username: ${DB_META_USERNAME}
    password: ${DB_META_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
      initialize-schema: always

  sql:
    init:
      mode: always
      data-locations: ${MASTER_DATA_PATH}
      encoding: UTF-8
      continue-on-error: false

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN
