name: CI/CD for Development (Docker Compose)

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  call-cicd-template:
    name: Call CI/CD Template for Development
    uses: ./.github/workflows/cicd-template.yml
    secrets: inherit
    with:
      environment: 'dev'
