name: CI/CD ECS for Production

# on:
#   push:
#     tags:
#       - '*'

on:
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: read

jobs:
  call-cicd-template:
    name: Call CI/CD ECS Template for Production
    uses: ./.github/workflows/cicd-ecs-template.yml
    secrets: inherit
    with:
      environment: 'prod'
