name: CI/CD ECS for Development

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  call-cicd-template:
    name: Call CI/CD ECS Template for Development
    uses: ./.github/workflows/cicd-ecs-template.yml
    secrets: inherit
    with:
      environment: 'dev'
